# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKip1njHZwm-dVhWWgMsb9ZgHmEFvDke
"""

def MU (posiçãoinicial, velocidade, tempo):
  posição = (posiçãoinicial + velocidade * tempo)
  print (posição)

def MUV (posiçãoinicial, velocidade, aceleração, tempo):
  posição = (posiçãoinicial + (velocidade * tempo) + ((aceleração / 2) * tempo ** 2))
  print (posição)



import time

opcao = int (input ("Você deseja resolver um problema de Movimento Uniforme (MU = 0) ou de Movimento Uniformemente Variado (MUV = 1)? \n"))

while True:
  if opcao == 0:
    print ("\nOlá, seja bem vindo! \nVamos determinar a posição de um móvel a partir de sua posição inicial, velocidade e tempo:")
    time.sleep (1)

    x = int (input ("\nQual é a posição inicial em metros? \n"))
    time.sleep (1)

    v = int (input ("\nQual é a velocidade, em metros por segundo, do móvel? \n"))
    time.sleep (1)

    t = int (input ("\nQual é o tempo, em segundos, gasto no movimento? \n"))
    time.sleep (1)

    print ("\nA posição final do móvel, em metros, será: ")
    MU (x,v,t)
    print ("_______________________________________________________________________________________________________________\n")
    time.sleep (1)

    opcao = int (input ("\nVocê gostaria de determinar uma posição no MU (0), no MUV (1) ou encerrar o programa (2): \n "))

  elif opcao == 1:
    print ("\nOlá, seja bem vindo! \nVamos determinar a posição de um móvel a partir de sua posição inicial, velocidade, aceleração e tempo:")
    time.sleep (1)

    x = int (input ("\nQual é a posição inicial em metros? \n"))
    time.sleep (1)

    v = int (input ("\nQual é a velocidade, em metros por segundo, do móvel? \n"))
    time.sleep (1)

    a = int (input ("\nQual é a aceleração, em metros por segundo ao quadrado, do móvel? \n"))
    time.sleep (1)

    t = int (input ("\nQual é o tempo, em segundos, gasto no movimento? \n"))
    time.sleep (1)

    print ("\nA posição final do móvel, em metros, será: ")

    MUV (x,v,a,t)
    print ("_______________________________________________________________________________________________________________\n")
    time.sleep (1)

    opcao = int (input ("\nVocê gostaria de determinar uma posição no MU (0), no MUV (1) ou encerrar o programa (2): \n "))

  else:
    break

1